// One-time generator: parses the bundled sample xlsx into a typed TS module.
// Run from packages/demo-video/: npm run gen-data
import XLSX from 'xlsx';
import {writeFileSync} from 'node:fs';
import {resolve} from 'node:path';

const SRC = resolve(process.cwd(), '../../AeroInsights_SamplePortfolio_2026.xlsx');
const wb = XLSX.readFile(SRC);
const rows = (name) => XLSX.utils.sheet_to_json(wb.Sheets[name], {header: 1, blankrows: false});

// Aircraft Register: row0=title, row1=headers, row2+=data
// Headers: AC ID, Registration, MSN, Type, Manufacturer, Vintage, Age (yr), Family,
//          Operator, Country, Stage, Current MV ($M), EAD ($M), Monthly Rent ($k), ...
const aircraft = rows('Aircraft Register').slice(2).map((r) => ({
  id: r[0], reg: r[1], type: r[3], operator: r[8], country: r[9],
  stage: Number(r[10]), mv: Number(r[11]), ead: Number(r[12]), rent: Number(r[13]),
})).filter((a) => a.id && String(a.id).startsWith('AC-'));

// Lessee Profiles: row0=title, row1=headers, row2+=data
// Headers: Lessee ID, Name, IATA, Country, Region, Credit Rating, PD Estimate,
//          Watchlist, Stage, DPD (days), ...
const lessees = rows('Lessee Profiles').slice(2).map((r) => ({
  id: r[0], name: r[1], country: r[3], rating: r[5], pd: Number(r[6]),
  watchlist: String(r[7] || '').toLowerCase(), stage: r[8], dpd: Number(r[9]),
})).filter((l) => l.id && String(l.id).startsWith('LSE-'));

const out = `// AUTO-GENERATED by scripts/gen-data.mjs from AeroInsights_SamplePortfolio_2026.xlsx
// Do not edit by hand; re-run \`npm run gen-data\`.
export interface Aircraft { id: string; reg: string; type: string; operator: string; country: string; stage: number; mv: number; ead: number; rent: number; }
export interface Lessee { id: string; name: string; country: string; rating: string; pd: number; watchlist: string; stage: string; dpd: number; }

export const LESSOR = 'Aer Capital Partners Ltd.';
export const REPORTING_DATE = '31 May 2026';
export const AIRCRAFT: Aircraft[] = ${JSON.stringify(aircraft, null, 2)};
export const LESSEES: Lessee[] = ${JSON.stringify(lessees, null, 2)};

// Headline figures used by the Dashboard KPI strip (see spec §4).
export const KPIS = {
  portfolioValue: '$2.41B',
  fleetSize: AIRCRAFT.length,
  avgLtv: '67.3%',
  eclReserve: '$47.2M',
} as const;

// Stress scenario outputs (Stress Scenarios sheet, spec §4 Scene 4).
export const SCENARIOS = [
  {label: 'Base', value: '$47.2M', weight: 60, status: 'green' as const},
  {label: 'Adverse', value: '$58.9M', weight: 25, status: 'amber' as const},
  {label: 'Severe', value: '$71.4M', weight: 15, status: 'red' as const},
];

// One worked IFRS 9 ECL row highlighted in Scene 3.
export const ECL_HIGHLIGHT = {
  lessee: 'IndiGo Airlines', ead: '$24.2M', pdLifetime: 0.85, lgd: 0.45,
  eclLifetime: '$4.2M', dpd: 47, stage: 'Stage 3',
};
`;

writeFileSync(resolve(process.cwd(), 'src/data/portfolio.ts'), out);
console.log('Wrote src/data/portfolio.ts:', aircraft.length, 'aircraft,', lessees.length, 'lessees');
