"""initial schema

Revision ID: 85734ba34a2f
Revises: 
Create Date: 2026-05-04 11:09:03.092621

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '85734ba34a2f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('before_hash', sa.String(length=64), nullable=True),
    sa.Column('after_hash', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('exports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('data_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exports_tenant_id'), 'exports', ['tenant_id'], unique=False)
    op.create_table('scenario_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('inputs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('weight_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_templates_tenant_id'), 'scenario_templates', ['tenant_id'], unique=False)
    op.create_table('scheduled_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=True),
    sa.Column('run_time', sa.String(length=5), nullable=False),
    sa.Column('recipients_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('report_template_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_reports_tenant_id'), 'scheduled_reports', ['tenant_id'], unique=False)
    op.create_table('sicr_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('dpd_enabled', sa.Boolean(), nullable=False),
    sa.Column('dpd_days', sa.Integer(), nullable=False),
    sa.Column('upgrade_enabled', sa.Boolean(), nullable=False),
    sa.Column('upgrade_notches', sa.Integer(), nullable=False),
    sa.Column('country_watchlist_enabled', sa.Boolean(), nullable=False),
    sa.Column('insolvency_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_index(op.f('ix_sicr_config_tenant_id'), 'sicr_config', ['tenant_id'], unique=False)
    op.create_table('stage_migrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('lease_id', sa.String(length=36), nullable=False),
    sa.Column('from_stage', sa.String(length=1), nullable=False),
    sa.Column('to_stage', sa.String(length=1), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('migration_date', sa.Date(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_migrations_lease_id'), 'stage_migrations', ['lease_id'], unique=False)
    op.create_index(op.f('ix_stage_migrations_tenant_id'), 'stage_migrations', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('primary_currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('fiscal_year_end', sa.String(length=10), nullable=False),
    sa.Column('ifrs9_adoption_date', sa.Date(), nullable=True),
    sa.Column('default_discount_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_config',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('signal_weights_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('red_threshold', sa.Integer(), nullable=False),
    sa.Column('amber_threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_index(op.f('ix_watchlist_config_tenant_id'), 'watchlist_config', ['tenant_id'], unique=False)
    op.create_table('aircraft',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('msn', sa.String(length=20), nullable=False),
    sa.Column('aircraft_type', sa.String(length=50), nullable=False),
    sa.Column('registration', sa.String(length=20), nullable=True),
    sa.Column('vintage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aircraft_tenant_id'), 'aircraft', ['tenant_id'], unique=False)
    op.create_table('lessees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('credit_rating', sa.String(length=10), nullable=True),
    sa.Column('stage', sa.Enum('stage1', 'stage2', 'stage3', name='leasestage'), nullable=False),
    sa.Column('watchlist_status', sa.Enum('green', 'amber', 'red', name='watchliststatus'), nullable=False),
    sa.Column('behavior_score', sa.Integer(), nullable=True),
    sa.Column('behavior_scores_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessees_tenant_id'), 'lessees', ['tenant_id'], unique=False)
    op.create_table('scenario_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.Enum('deterministic', 'montecarlo', name='runmode'), nullable=False),
    sa.Column('paths', sa.Integer(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('inputs_hash', sa.String(length=64), nullable=False),
    sa.Column('portfolio_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('ecl_result', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('p5', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('p95', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('s1_ecl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('s2_ecl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('s3_ecl', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('shapley_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('key_finding', sa.Text(), nullable=True),
    sa.Column('duration_sec', sa.String(length=20), nullable=True),
    sa.Column('scenario_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['scenario_templates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_runs_tenant_id'), 'scenario_runs', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('auth0_sub', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'risk', 'accounting', 'readonly', name='userrole'), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email')
    )
    op.create_index(op.f('ix_users_auth0_sub'), 'users', ['auth0_sub'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('behavior_score_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lessee_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('sub_scores_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lessee_id'], ['lessees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_behavior_score_history_lessee_id'), 'behavior_score_history', ['lessee_id'], unique=False)
    op.create_index(op.f('ix_behavior_score_history_tenant_id'), 'behavior_score_history', ['tenant_id'], unique=False)
    op.create_table('leases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('lessee_id', sa.String(length=36), nullable=False),
    sa.Column('aircraft_id', sa.String(length=36), nullable=False),
    sa.Column('lease_start', sa.Date(), nullable=False),
    sa.Column('lease_end', sa.Date(), nullable=False),
    sa.Column('monthly_rent_usd', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('stage', sa.Enum('stage1', 'stage2', 'stage3', name='leasestage'), nullable=False),
    sa.Column('status', sa.Enum('active', 'terminated', 'expired', name='leasestatus'), nullable=False),
    sa.Column('sicr_trigger', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ),
    sa.ForeignKeyConstraint(['lessee_id'], ['lessees.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leases_aircraft_id'), 'leases', ['aircraft_id'], unique=False)
    op.create_index(op.f('ix_leases_lessee_id'), 'leases', ['lessee_id'], unique=False)
    op.create_index(op.f('ix_leases_tenant_id'), 'leases', ['tenant_id'], unique=False)
    op.create_table('run_lease_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('lease_id', sa.String(length=36), nullable=False),
    sa.Column('pd_12m', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('pd_lifetime', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('lgd', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('ead', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ecl_12m', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ecl_lifetime', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('stage', sa.String(length=1), nullable=True),
    sa.Column('journal_movement', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['scenario_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_lease_results_lease_id'), 'run_lease_results', ['lease_id'], unique=False)
    op.create_index(op.f('ix_run_lease_results_run_id'), 'run_lease_results', ['run_id'], unique=False)
    op.create_table('valuations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('aircraft_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.Enum('heuristic', 'avitas', 'cirium', 'iba', 'user', name='valuationsource'), nullable=False),
    sa.Column('half_life_base', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('current_mv', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('mav', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('lease_encumbered', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('part_out', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('uncertainty_band_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aircraft_id'], ['aircraft.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valuations_aircraft_id'), 'valuations', ['aircraft_id'], unique=False)
    op.create_index(op.f('ix_valuations_tenant_id'), 'valuations', ['tenant_id'], unique=False)
    op.create_table('ecl_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lease_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=True),
    sa.Column('scenario_weights_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weighted_ecl_12m', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('weighted_ecl_lifetime', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('stage', sa.Enum('stage1', 'stage2', 'stage3', name='leasestage'), nullable=False),
    sa.Column('sicr_trigger', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecl_records_lease_id'), 'ecl_records', ['lease_id'], unique=False)
    op.create_index(op.f('ix_ecl_records_tenant_id'), 'ecl_records', ['tenant_id'], unique=False)
    op.create_table('maintenance_reserves',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lease_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('component', sa.String(length=100), nullable=False),
    sa.Column('rate_basis', sa.String(length=20), nullable=False),
    sa.Column('rate_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('refundable', sa.Boolean(), nullable=False),
    sa.Column('cap_rule', sa.Text(), nullable=True),
    sa.Column('cumulative_balance', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_reserves_lease_id'), 'maintenance_reserves', ['lease_id'], unique=False)
    op.create_index(op.f('ix_maintenance_reserves_tenant_id'), 'maintenance_reserves', ['tenant_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lease_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.Column('amount_usd', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('days_late', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_lease_id'), 'payments', ['lease_id'], unique=False)
    op.create_index(op.f('ix_payments_tenant_id'), 'payments', ['tenant_id'], unique=False)
    op.create_table('security_deposits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lease_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('sd_type', sa.Enum('cash', 'lc', name='sdtype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('refund_triggers', sa.Text(), nullable=True),
    sa.Column('governing_law', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lease_id'], ['leases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_deposits_lease_id'), 'security_deposits', ['lease_id'], unique=False)
    op.create_index(op.f('ix_security_deposits_tenant_id'), 'security_deposits', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_deposits_tenant_id'), table_name='security_deposits')
    op.drop_index(op.f('ix_security_deposits_lease_id'), table_name='security_deposits')
    op.drop_table('security_deposits')
    op.drop_index(op.f('ix_payments_tenant_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_lease_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_maintenance_reserves_tenant_id'), table_name='maintenance_reserves')
    op.drop_index(op.f('ix_maintenance_reserves_lease_id'), table_name='maintenance_reserves')
    op.drop_table('maintenance_reserves')
    op.drop_index(op.f('ix_ecl_records_tenant_id'), table_name='ecl_records')
    op.drop_index(op.f('ix_ecl_records_lease_id'), table_name='ecl_records')
    op.drop_table('ecl_records')
    op.drop_index(op.f('ix_valuations_tenant_id'), table_name='valuations')
    op.drop_index(op.f('ix_valuations_aircraft_id'), table_name='valuations')
    op.drop_table('valuations')
    op.drop_index(op.f('ix_run_lease_results_run_id'), table_name='run_lease_results')
    op.drop_index(op.f('ix_run_lease_results_lease_id'), table_name='run_lease_results')
    op.drop_table('run_lease_results')
    op.drop_index(op.f('ix_leases_tenant_id'), table_name='leases')
    op.drop_index(op.f('ix_leases_lessee_id'), table_name='leases')
    op.drop_index(op.f('ix_leases_aircraft_id'), table_name='leases')
    op.drop_table('leases')
    op.drop_index(op.f('ix_behavior_score_history_tenant_id'), table_name='behavior_score_history')
    op.drop_index(op.f('ix_behavior_score_history_lessee_id'), table_name='behavior_score_history')
    op.drop_table('behavior_score_history')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_auth0_sub'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scenario_runs_tenant_id'), table_name='scenario_runs')
    op.drop_table('scenario_runs')
    op.drop_index(op.f('ix_lessees_tenant_id'), table_name='lessees')
    op.drop_table('lessees')
    op.drop_index(op.f('ix_aircraft_tenant_id'), table_name='aircraft')
    op.drop_table('aircraft')
    op.drop_index(op.f('ix_watchlist_config_tenant_id'), table_name='watchlist_config')
    op.drop_table('watchlist_config')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_stage_migrations_tenant_id'), table_name='stage_migrations')
    op.drop_index(op.f('ix_stage_migrations_lease_id'), table_name='stage_migrations')
    op.drop_table('stage_migrations')
    op.drop_index(op.f('ix_sicr_config_tenant_id'), table_name='sicr_config')
    op.drop_table('sicr_config')
    op.drop_index(op.f('ix_scheduled_reports_tenant_id'), table_name='scheduled_reports')
    op.drop_table('scheduled_reports')
    op.drop_index(op.f('ix_scenario_templates_tenant_id'), table_name='scenario_templates')
    op.drop_table('scenario_templates')
    op.drop_index(op.f('ix_exports_tenant_id'), table_name='exports')
    op.drop_table('exports')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
