// AUTO-GENERATED by scripts/gen-data.mjs from AeroInsights_SamplePortfolio_2026.xlsx
// Do not edit by hand; re-run `npm run gen-data`.
export interface Aircraft { id: string; reg: string; type: string; operator: string; country: string; stage: number; mv: number; ead: number; rent: number; }
export interface Lessee { id: string; name: string; country: string; rating: string; pd: number; watchlist: string; stage: string; dpd: number; }

export const LESSOR = 'Aer Capital Partners Ltd.';
export const REPORTING_DATE = '31 May 2026';
export const AIRCRAFT: Aircraft[] = [
  {
    "id": "AC-01",
    "reg": "VT-IYC",
    "type": "A320neo",
    "operator": "IndiGo Airlines",
    "country": "India",
    "stage": 3,
    "mv": 36.5,
    "ead": 24.2,
    "rent": 285
  },
  {
    "id": "AC-02",
    "reg": "XA-AMX",
    "type": "B737-800",
    "operator": "Aeromexico",
    "country": "Mexico",
    "stage": 3,
    "mv": 32.1,
    "ead": 32.1,
    "rent": 310
  },
  {
    "id": "AC-03",
    "reg": "A6-ECE",
    "type": "B777-300ER",
    "operator": "Emirates",
    "country": "UAE",
    "stage": 1,
    "mv": 118,
    "ead": 88.4,
    "rent": 1240
  },
  {
    "id": "AC-04",
    "reg": "4R-ALB",
    "type": "A330-300",
    "operator": "SriLankan Airlines",
    "country": "Sri Lanka",
    "stage": 2,
    "mv": 48.2,
    "ead": 34.2,
    "rent": 480
  },
  {
    "id": "AC-05",
    "reg": "EI-HXP",
    "type": "B737 MAX 8",
    "operator": "Ryanair",
    "country": "Ireland",
    "stage": 1,
    "mv": 48.5,
    "ead": 44.7,
    "rent": 340
  },
  {
    "id": "AC-06",
    "reg": "F-HTYR",
    "type": "A350-900",
    "operator": "Air France",
    "country": "France",
    "stage": 1,
    "mv": 155,
    "ead": 68.3,
    "rent": 960
  },
  {
    "id": "AC-07",
    "reg": "PR-YRJ",
    "type": "A320neo",
    "operator": "Azul Brazilian Airlines",
    "country": "Brazil",
    "stage": 2,
    "mv": 41.2,
    "ead": 34.2,
    "rent": 295
  },
  {
    "id": "AC-08",
    "reg": "C-GTSA",
    "type": "A321neo",
    "operator": "Air Transat",
    "country": "Canada",
    "stage": 2,
    "mv": 50,
    "ead": 28.9,
    "rent": 275
  },
  {
    "id": "AC-09",
    "reg": "9V-SMB",
    "type": "A350-900",
    "operator": "Singapore Airlines",
    "country": "Singapore",
    "stage": 1,
    "mv": 178,
    "ead": 91.2,
    "rent": 1050
  },
  {
    "id": "AC-10",
    "reg": "D-AIVM",
    "type": "A220-300",
    "operator": "Lufthansa",
    "country": "Germany",
    "stage": 1,
    "mv": 57.5,
    "ead": 44.7,
    "rent": 220
  }
];
export const LESSEES: Lessee[] = [
  {
    "id": "LSE-01",
    "name": "IndiGo Airlines",
    "country": "India",
    "rating": "BB-",
    "pd": 0.12,
    "watchlist": "red",
    "stage": "Stage 3",
    "dpd": 47
  },
  {
    "id": "LSE-02",
    "name": "Aeromexico",
    "country": "Mexico",
    "rating": "CCC",
    "pd": 0.28,
    "watchlist": "red",
    "stage": "Stage 3",
    "dpd": 89
  },
  {
    "id": "LSE-03",
    "name": "Emirates",
    "country": "UAE",
    "rating": "A-",
    "pd": 0.01,
    "watchlist": "green",
    "stage": "Stage 1",
    "dpd": 0
  },
  {
    "id": "LSE-04",
    "name": "SriLankan Airlines",
    "country": "Sri Lanka",
    "rating": "B+",
    "pd": 0.08,
    "watchlist": "amber",
    "stage": "Stage 2",
    "dpd": 12
  },
  {
    "id": "LSE-05",
    "name": "Ryanair",
    "country": "Ireland",
    "rating": "BBB+",
    "pd": 0.02,
    "watchlist": "green",
    "stage": "Stage 1",
    "dpd": 32
  },
  {
    "id": "LSE-06",
    "name": "Air France",
    "country": "France",
    "rating": "BB+",
    "pd": 0.04,
    "watchlist": "green",
    "stage": "Stage 1",
    "dpd": 0
  },
  {
    "id": "LSE-07",
    "name": "Azul Brazilian Airlines",
    "country": "Brazil",
    "rating": "B+",
    "pd": 0.09,
    "watchlist": "amber",
    "stage": "Stage 2",
    "dpd": 38
  },
  {
    "id": "LSE-08",
    "name": "Air Transat",
    "country": "Canada",
    "rating": "B",
    "pd": 0.11,
    "watchlist": "amber",
    "stage": "Stage 2",
    "dpd": 35
  },
  {
    "id": "LSE-09",
    "name": "Singapore Airlines",
    "country": "Singapore",
    "rating": "A",
    "pd": 0.01,
    "watchlist": "green",
    "stage": "Stage 1",
    "dpd": 0
  },
  {
    "id": "LSE-10",
    "name": "Lufthansa",
    "country": "Germany",
    "rating": "BBB-",
    "pd": 0.03,
    "watchlist": "green",
    "stage": "Stage 1",
    "dpd": 0
  }
];

// Headline figures used by the Dashboard KPI strip (see spec §4).
export const KPIS = {
  portfolioValue: '$2.41B',
  fleetSize: AIRCRAFT.length,
  avgLtv: '67.3%',
  eclReserve: '$47.2M',
} as const;

// Stress scenario outputs (Stress Scenarios sheet, spec §4 Scene 4).
export const SCENARIOS = [
  {label: 'Base', value: '$47.2M', weight: 60, status: 'green' as const},
  {label: 'Adverse', value: '$58.9M', weight: 25, status: 'amber' as const},
  {label: 'Severe', value: '$71.4M', weight: 15, status: 'red' as const},
];

// One worked IFRS 9 ECL row highlighted in Scene 3.
export const ECL_HIGHLIGHT = {
  lessee: 'IndiGo Airlines', ead: '$24.2M', pdLifetime: 0.85, lgd: 0.45,
  eclLifetime: '$4.2M', dpd: 47, stage: 'Stage 3',
};
